module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Doctors', [{
      email: 'david6572@rambler.ru',
      password: 'qwerty',
      first_name: 'Давид',
      last_name: 'Дудкин',
      patronymic: 'Юлианович',
      telephone: '79998867458',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'уролог',
      photo: 'http://photo.com/photos30',
      sex: 'male',
      adress: 'Россия, г. Москва, Молодежная ул., д. 9',
      is_activated: false,
      activation_link: 'cewcewcw',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'timofey4023@yandex.ru',
      password: 'qwerty',
      first_name: 'Тимофей',
      last_name: 'Кузьмов',
      patronymic: '',
      telephone: '79997547237',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'уролог',
      photo: 'http://photo.com/photos40',
      sex: 'male',
      adress: 'Россия, г. Москва, Железнодорожная ул., д. 3',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'lavrentiy.ishutin@rambler.ru',
      password: 'qwerty',
      first_name: 'Лаврентий',
      last_name: 'Ишутин',
      patronymic: 'Климентович',
      telephone: '79990885317',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'уролог',
      photo: 'http://photo.com/photos41',
      sex: 'male',
      adress: 'Россия, г. Омск, Победы ул., д. 12',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'alena68@ya.ru',
      password: 'qwerty',
      first_name: 'Алена',
      last_name: 'Самошина',
      patronymic: 'Кирилловна',
      telephone: '79992419049',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'уролог',
      photo: 'http://photo.com/photos41',
      sex: 'female',
      adress: 'Россия, г. Казань, Первомайский пер., д. 4',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'yuliana6313@yandex.ru',
      password: 'qwerty',
      first_name: 'Юлиана',
      last_name: 'Русанова',
      patronymic: 'Трофимовна',
      telephone: '79993567042',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'проктолог',
      photo: 'http://photo.com/photos42',
      sex: 'female',
      adress: 'Россия, г. Москва, 17 Сентября ул., д. 19',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'grigoriy1995@outlook.com',
      password: 'qwerty',
      first_name: 'Григорий',
      last_name: 'Борцов',
      patronymic: '',
      telephone: '79999662936',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'проктолог',
      photo: 'http://photo.com/photos43',
      sex: 'male',
      adress: 'Россия, г. Казань, Дружная ул., д. 18',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'anna1978@yandex.ru',
      password: 'qwerty',
      first_name: 'Анна',
      last_name: 'Ревягина',
      patronymic: 'Ефимовна',
      telephone: '79991554633',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'терапевт',
      photo: 'http://photo.com/photos44',
      sex: 'female',
      adress: 'Россия, г. Москва, Гагарина ул., д. 5',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'mila05071960@gmail.com',
      password: 'qwerty',
      first_name: 'Мила',
      last_name: 'Ульяшина',
      patronymic: 'Яковна',
      telephone: '79997577066',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'терапевт',
      photo: 'http://photo.com/photos45',
      sex: 'female',
      adress: 'Россия, г. Москва, Школьный пер., д. 5',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'valentin1989@gmail.com',
      password: 'qwerty',
      first_name: 'Валентин',
      last_name: 'Балинский',
      patronymic: 'Валентинович',
      telephone: '79992213631',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'терапевт',
      photo: 'http://photo.com/photos46',
      sex: 'male',
      adress: 'Россия, г. Омск, Песчаная ул., д. 19',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'valentin1989@gmail.com',
      password: 'qwerty',
      first_name: 'Павел',
      last_name: 'Зуб',
      patronymic: 'Семенович',
      telephone: '79999899159',
      experience: 'This method is not a part of Sequelize lifecycle.',
      education: 'The `models/index` file will call this method automatically.',
      speciality: 'психиатр',
      photo: 'http://photo.com/photos46',
      sex: 'male',
      adress: 'Россия, г. Москва, Сельская ул., д. 24',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'shestakovoa@gmail.com',
      password: '$2b$10$zmXSXny8UyqISe4yH70KgeP5AtABnmrQ9ylI9sDRhWLE5JeWaeVJu',
      first_name: 'Олег',
      last_name: 'Шестаков',
      patronymic: 'Александрович',
      telephone: '79999899159',
      experience: 'без опыта',
      education: 'плохое',
      speciality: 'психиатр',
      photo: 'http://photo.com/photos46',
      sex: 'male',
      adress: 'Россия, г. Москва, Ленина ул., д. 1',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], { });
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Doctors', null, {});
  },
};
