module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [{
      email: 'freetime@freetime.com',
      password: 'freetime',
      first_name: 'Сергей',
      last_name: 'Гончаров',
      patronymic: 'Иванович',
      telephone: '80000000000',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'freetime',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'vennuttucrici-9207@yopmail.com',
      password: 'qwerty',
      first_name: 'Петр',
      last_name: 'Бочкин',
      patronymic: 'Васильевич',
      telephone: '88005553535',
      photo: null,
      sex: 'other',
      is_activated: true,
      activation_link: 'vrrrvvrr',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'meuvappogritoi-9696@yopmail.com',
      password: 'qwerty',
      first_name: 'Василий',
      last_name: 'Кочкин',
      patronymic: '',
      telephone: '88009999999',
      photo: null,
      sex: 'male',
      is_activated: false,
      activation_link: 'qwqwqwwqwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'crussizaquousau-4822@yopmail.com',
      password: 'qwerty',
      first_name: 'Константин',
      last_name: 'Почкин',
      patronymic: 'Эдуардович',
      telephone: '74958553770',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'qwqwqwwqwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'zeufoutteixusau-3626@yopmail.com',
      password: 'qwerty',
      first_name: 'Есения',
      last_name: 'Устинова',
      patronymic: 'Тимофеевна',
      telephone: '74958444566',
      photo: null,
      sex: 'female',
      is_activated: true,
      activation_link: 'qwqwqwwqffewwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'vullotoquapou-4059@yopmail.com',
      password: 'qwerty',
      first_name: 'Софья',
      last_name: 'Майорова',
      patronymic: 'Фёдоровна',
      telephone: '74955653926',
      photo: null,
      sex: 'female',
      is_activated: true,
      activation_link: 'qwqdewdwqwwqffewwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'crepeijabruproi-3471@yopmail.com',
      password: 'qwerty',
      first_name: 'Кирилл',
      last_name: 'Губанов',
      patronymic: 'Ильич',
      telephone: '74954661145',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'qwqdewcsddwqwwqffewwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'keivammotuppeu-4361@yopmail.com',
      password: 'qwerty',
      first_name: 'Тимофей',
      last_name: 'Ильин',
      patronymic: 'Арсентьевич',
      telephone: '74959137842',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'qwqdewcsddwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'reikupihehu-3628@yopmail.com',
      password: 'qwerty',
      first_name: 'Ярослав',
      last_name: 'Овсянников',
      patronymic: 'Константинович',
      telephone: '74958724395',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'qwqdcesewcsddwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'achtung@gmail.com',
      password: '$2b$10$zmXSXny8UyqISe4yH70KgeP5AtABnmrQ9ylI9sDRhWLE5JeWaeVJu',
      first_name: 'Иван',
      last_name: 'Петров',
      patronymic: 'Александрович',
      telephone: '71242112414',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'qwqdcesewcsddwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'reikupihehu-3628@yopmail.com',
      password: 'qwerty',
      first_name: 'Иван',
      last_name: 'Овсянников',
      patronymic: 'Васильевич',
      telephone: '74958724395',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'qwqdcesewcsddwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'reikupihehu-3628@yopmail.com',
      password: 'qwerty',
      first_name: 'Андрей',
      last_name: 'Марченко',
      patronymic: 'Константинович',
      telephone: '74958724395',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'qwqdcesewcsddwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'reikupihehu-3628@yopmail.com',
      password: 'qwerty',
      first_name: 'Артем',
      last_name: 'Артемьев',
      patronymic: 'Гаврилович',
      telephone: '74958724395',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'qwqdcesewcsddwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'reikupihehu-3628@yopmail.com',
      password: 'qwerty',
      first_name: 'Иван',
      last_name: 'Бондаренко',
      patronymic: 'Иванович',
      telephone: '74958724395',
      photo: null,
      sex: 'male',
      is_activated: true,
      activation_link: 'qwqdcesewcsddwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'reikupihehu-3628@yopmail.com',
      password: 'qwerty',
      first_name: 'Елена',
      last_name: 'Овчаренко',
      patronymic: 'Воадимировна',
      telephone: '74958724395',
      photo: null,
      sex: 'female',
      is_activated: true,
      activation_link: 'qwqdcesewcsddwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'reikupihehu-3628@yopmail.com',
      password: 'qwerty',
      first_name: 'Ярослава',
      last_name: 'Короткова',
      patronymic: 'Евгеньевна',
      telephone: '74958724395',
      photo: null,
      sex: 'female',
      is_activated: true,
      activation_link: 'qwqdcesewcsddwqwq',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};

// email: ,
//   password: ,
// first_name: ,
//   last_name: ,
// patronymic: ,
//   telephone: ,
// photo: ,
//   sex: ,
// is_activated: ,
//   activation_link: ,
// createdAt: ,
//   updatedAt: ,
