module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Doctors', [{
      email: 'david6572@rambler.ru',
      password: 'qwerty',
      first_name: 'Давид',
      last_name: 'Дудкин',
      patronymic: 'Юлианович',
      telephone: '79998867458',
      experience: '25 лет',
      education: 'Высшая категория, кандидат наук',
      speciality: 'уролог',
      photo: 'male1.jpeg',
      sex: 'male',
      adress: 'Россия, г. Москва, Молодежная ул., д. 9',
      is_activated: false,
      activation_link: 'cewcewcw',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'timofey4023@yandex.ru',
      password: 'qwerty',
      first_name: 'Тимофей',
      last_name: 'Кузьмов',
      patronymic: '',
      telephone: '79997547237',
      experience: '10 лет',
      education: '1 категория',
      speciality: 'уролог',
      photo: 'male2.jpeg',
      sex: 'male',
      adress: 'Россия, г. Москва, Железнодорожная ул., д. 3',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'lavrentiy.ishutin@rambler.ru',
      password: 'qwerty',
      first_name: 'Лаврентий',
      last_name: 'Ишутин',
      patronymic: 'Климентович',
      telephone: '79990885317',
      experience: '12 лет',
      education: '1 категория',
      speciality: 'уролог',
      photo: 'male3.jpeg',
      sex: 'male',
      adress: 'Россия, г. Омск, Победы ул., д. 12',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'alena68@ya.ru',
      password: 'qwerty',
      first_name: 'Алена',
      last_name: 'Самошина',
      patronymic: 'Кирилловна',
      telephone: '79992419049',
      experience: '14 лет',
      education: 'Высшая категория',
      speciality: 'уролог',
      photo: 'female1.jpeg',
      sex: 'female',
      adress: 'Россия, г. Казань, Первомайский пер., д. 4',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'yuliana6313@yandex.ru',
      password: 'qwerty',
      first_name: 'Юлиана',
      last_name: 'Русанова',
      patronymic: 'Трофимовна',
      telephone: '79993567042',
      experience: '20 лет',
      education: 'Высшая категория, кандидат наук',
      speciality: 'проктолог',
      photo: 'female2.jpeg',
      sex: 'female',
      adress: 'Россия, г. Москва, 17 Сентября ул., д. 19',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'grigoriy1995@outlook.com',
      password: 'qwerty',
      first_name: 'Григорий',
      last_name: 'Борцов',
      patronymic: '',
      telephone: '79999662936',
      experience: '11 лет',
      education: 'Высшая категория',
      speciality: 'проктолог',
      photo: 'male4.jpeg',
      sex: 'male',
      adress: 'Россия, г. Казань, Дружная ул., д. 18',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'anna1978@yandex.ru',
      password: 'qwerty',
      first_name: 'Анна',
      last_name: 'Ревягина',
      patronymic: 'Ефимовна',
      telephone: '79991554633',
      experience: '7 лет',
      education: '2 категория',
      speciality: 'терапевт',
      photo: 'female3.jpeg',
      sex: 'female',
      adress: 'Россия, г. Москва, Гагарина ул., д. 5',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'mila05071960@gmail.com',
      password: 'qwerty',
      first_name: 'Мила',
      last_name: 'Ульяшина',
      patronymic: 'Яковна',
      telephone: '79997577066',
      experience: '14 лет',
      education: '1 категория',
      speciality: 'терапевт',
      photo: 'female4.jpeg',
      sex: 'female',
      adress: 'Россия, г. Москва, Школьный пер., д. 5',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'valentin1989@gmail.com',
      password: 'qwerty',
      first_name: 'Валентин',
      last_name: 'Балинский',
      patronymic: 'Валентинович',
      telephone: '79992213631',
      experience: '20 лет',
      education: 'Высшая категория',
      speciality: 'терапевт',
      photo: 'male5.jpeg',
      sex: 'male',
      adress: 'Россия, г. Омск, Песчаная ул., д. 19',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'valentin1989@gmail.com',
      password: 'qwerty',
      first_name: 'Павел',
      last_name: 'Зуб',
      patronymic: 'Семенович',
      telephone: '79999899159',
      experience: '7 лет',
      education: '2 категория',
      speciality: 'психиатр',
      photo: 'male6.jpeg',
      sex: 'male',
      adress: 'Россия, г. Москва, Сельская ул., д. 24',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      email: 'achtung@gmail.com',
      password: '$2b$10$zmXSXny8UyqISe4yH70KgeP5AtABnmrQ9ylI9sDRhWLE5JeWaeVJu',
      first_name: 'Иван',
      last_name: 'Петров',
      patronymic: 'Александрович',
      telephone: '79999899159',
      experience: '14 лет',
      education: 'Высшая категория, кандидат наук',
      speciality: 'психиатр',
      photo: 'male7.jpeg',
      sex: 'male',
      adress: 'Россия, г. Москва, Ленина ул., д. 1',
      is_activated: true,
      activation_link: 'cewvaerwvrvrwe',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], { });
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Doctors', null, {});
  },
};
